### ISSUE TITLE
네트워키오가 보안지식 문서 일부 항목 포멧 오류

### ISSUE THREAD

**Issue by taisetna** [liante0904/synology-beginner-guide#1]
해당 문서 내 하기 첨부한 그림과 같이 DMZ 항목에 마크다운이 정상적으로 적용되지 않았습니다.

![image](https://user-images.githubusercontent.com/29498969/51072798-6a965800-16aa-11e9-9ca1-34d35b9ca364.png)

**Comment by liante0904** [comment]
수고스럽게 이미지까지..! 
감사합니다. 다음 push때 반영해서 내용 추가하겠습니다.
